[build]
  command = "CI= npm run build"
  publish = "/dist"


[[redirects]]
  from = "/api/*"
  to = "https://amanii-resources.up.railway.app/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200